name: Render document with Nix and Quarto and create a Release

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        logger: pretty
        log-directives: nix_installer=trace
        backtrace: full

    - name: Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Build development environment
      run: |
        nix-build

    - name: Render
      run: nix-shell --run "quarto render"
      
    - uses: ncipollo/release-action@v1
          with:
            artifacts: "_book/Book-Title.pdf"
            bodyFile: "release.md"
